// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxiCUqAT7H8ZM9B0KmAohpf8UtLkUGMbQ',
    appId: '1:466454291182:web:c01dcd87699db996b2c9ff',
    messagingSenderId: '466454291182',
    projectId: 'hostelaudit-c42d4',
    authDomain: 'hostelaudit-c42d4.firebaseapp.com',
    storageBucket: 'hostelaudit-c42d4.firebasestorage.app',
    measurementId: 'G-DC4T8GYVFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBq1vR78wLKNM9w7onS5mnMeQKIUxz2U',
    appId: '1:466454291182:android:bb0f1cdaa52f84e2b2c9ff',
    messagingSenderId: '466454291182',
    projectId: 'hostelaudit-c42d4',
    storageBucket: 'hostelaudit-c42d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8AASQoRowmjIhJ5wovXfrk-jGeHMgUlc',
    appId: '1:466454291182:ios:c64c944f8198bfedb2c9ff',
    messagingSenderId: '466454291182',
    projectId: 'hostelaudit-c42d4',
    storageBucket: 'hostelaudit-c42d4.firebasestorage.app',
    iosBundleId: 'com.example.hostelAuditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8AASQoRowmjIhJ5wovXfrk-jGeHMgUlc',
    appId: '1:466454291182:ios:c64c944f8198bfedb2c9ff',
    messagingSenderId: '466454291182',
    projectId: 'hostelaudit-c42d4',
    storageBucket: 'hostelaudit-c42d4.firebasestorage.app',
    iosBundleId: 'com.example.hostelAuditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxiCUqAT7H8ZM9B0KmAohpf8UtLkUGMbQ',
    appId: '1:466454291182:web:935a68558c666726b2c9ff',
    messagingSenderId: '466454291182',
    projectId: 'hostelaudit-c42d4',
    authDomain: 'hostelaudit-c42d4.firebaseapp.com',
    storageBucket: 'hostelaudit-c42d4.firebasestorage.app',
    measurementId: 'G-LQCBP4YYS0',
  );
}
