-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'supervisor', 'auditor')) default 'auditor',
  hostel_id uuid references public.hostels(id),
  created_at timestamptz default now()
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Create template_sections table
create table public.template_sections (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ms text not null,
  position int not null,
  version int default 1,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- Create template_items table
create table public.template_items (
  id bigint generated by default as identity primary key,
  section_id bigint references public.template_sections(id) on delete cascade,
  name_en text not null,
  name_ms text not null,
  position int not null,
  is_critical boolean default false,
  requires_photo boolean default false,
  created_at timestamptz default now()
);

-- Enable RLS on templates
alter table public.template_sections enable row level security;
alter table public.template_items enable row level security;

-- Allow read access to authenticated users
create policy "Enable read access for authenticated users" on public.template_sections for select using (auth.role() = 'authenticated');
create policy "Enable read access for authenticated users" on public.template_items for select using (auth.role() = 'authenticated');

-- Allow write access to admins (simplified for now: allow authenticated to write, should be restricted later)
create policy "Enable insert for authenticated users" on public.template_sections for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users" on public.template_sections for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users" on public.template_sections for delete using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users" on public.template_items for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users" on public.template_items for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users" on public.template_items for delete using (auth.role() = 'authenticated');

-- Insert default template data (Version 1)
-- Section 1: External/ Surrounding
insert into public.template_sections (name_en, name_ms, position) values ('External/ Surrounding', 'Luaran/ Persekitaran', 0);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Area hanging clothes', 'Kawasan ampaian', 0 from public.template_sections where name_en = 'External/ Surrounding';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cleanliness', 'Kebersihan', 1 from public.template_sections where name_en = 'External/ Surrounding';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Safety (door lock, gate)', 'Keselamatan (Mangga pintu, pintu pagar)', 2 from public.template_sections where name_en = 'External/ Surrounding';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Shoe Rack', 'Rak Kasut', 3 from public.template_sections where name_en = 'External/ Surrounding';

-- Section 2: Living room
insert into public.template_sections (name_en, name_ms, position) values ('Living room', 'Ruang Tamu', 1);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Notice board & Housekeeping Schedule', 'Papan notis & Jadual Pengemasan', 0 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Emergency Contact Information', 'Maklumat Pangilan Kecemasan', 1 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cleanliness', 'Kebersihan', 2 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Lamp', 'Lampu', 3 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Fan', 'Kipas', 4 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Fire Evacution Plan', 'Pelan Laluan Kebakaran', 5 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Facilities & Utility ( fans, lamp, sofa, TV, curtain)', 'Kemudahan & Utiliti (kipas, lampu, sofa, TV, langsir)', 6 from public.template_sections where name_en = 'Living room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Curtains', 'Langsir', 7 from public.template_sections where name_en = 'Living room';

-- Section 3: Dining Room
insert into public.template_sections (name_en, name_ms, position) values ('Dining Room', 'Ruang makan', 2);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Facilities & Utility ( dining table, chair, lamp)', 'Kemudahan & Utiliti ( meja makan, kerusi, lampu)', 0 from public.template_sections where name_en = 'Dining Room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cleanliness', 'Kebersihan', 1 from public.template_sections where name_en = 'Dining Room';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Lamp', 'Lampu', 2 from public.template_sections where name_en = 'Dining Room';

-- Section 4: Kitchen Facilities
insert into public.template_sections (name_en, name_ms, position) values ('Kitchen Facilities', 'Kemudahan Dapur', 3);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cooking Facilities', 'Kelengkapan Memasak', 0 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Sink & Tap', 'Sinki & Paip', 1 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Lamp', 'Lampu', 2 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cleanliness', 'Kebersihan', 3 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Emergency Response: Fire extinguisher', 'Tindak Balas Kecemasan: Alat pemadam api', 4 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Smoke Detector', 'Pengesan asap', 5 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Refrigerator', 'Peti sejuk', 6 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Food cabinet/ Rack', 'Kabinet makanan/ Rak', 7 from public.template_sections where name_en = 'Kitchen Facilities';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Dustbin', 'Tong sampah', 8 from public.template_sections where name_en = 'Kitchen Facilities';

-- Section 5: Bedroom
insert into public.template_sections (name_en, name_ms, position) values ('Bedroom', 'Bilik tidur', 4);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cleanliness & Tidiness (food not allow in room)', 'Kebersihan & Kekemasan (makanan tidak dibenarkan di dalam bilik)', 0 from public.template_sections where name_en = 'Bedroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Lamp', 'Lampu', 1 from public.template_sections where name_en = 'Bedroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Fan', 'Kipas', 2 from public.template_sections where name_en = 'Bedroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Double-Decker', 'Katil Bertingkat', 3 from public.template_sections where name_en = 'Bedroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Wardrobe Condition', 'Keadaan Almari Pakaian', 4 from public.template_sections where name_en = 'Bedroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Minimum 1 adapter each room', 'Minima 1 adapter (plug tiga soket) setiap bilik', 5 from public.template_sections where name_en = 'Bedroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Additional Item: curtain, carpet, pillow, blanket, bed', 'Item tambahan: langsir, permaidani, bantal, selimut, katil', 6 from public.template_sections where name_en = 'Bedroom';

-- Section 6: Washroom
insert into public.template_sections (name_en, name_ms, position) values ('Washroom', 'Bilik air', 5);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Cleanliness', 'Kebersihan', 0 from public.template_sections where name_en = 'Washroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Lamp', 'Lampu', 1 from public.template_sections where name_en = 'Washroom';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Facility & Utility ( shower, tap, basin, hole trap)', 'Kemudahan & Utiliti (paip mandi, paip, singki, lubang tandas)', 2 from public.template_sections where name_en = 'Washroom';

-- Section 7: Others
insert into public.template_sections (name_en, name_ms, position) values ('Others', 'Lain-lain', 6);
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'First-aid Kits', 'Peti pertolongan cemas', 0 from public.template_sections where name_en = 'Others';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Fire Extinguisher', 'Alat Pemadam Api', 1 from public.template_sections where name_en = 'Others';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Emergency Light', 'Lampu Kecemasan', 2 from public.template_sections where name_en = 'Others';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Smoke Detactor', 'Pengesan asap', 3 from public.template_sections where name_en = 'Others';
insert into public.template_items (section_id, name_en, name_ms, position) 
select id, 'Exit Signage', 'Papan Tanda Keluar', 4 from public.template_sections where name_en = 'Others';
